### ISSUE TITLE
Nothing is suggested

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_research_suggestions#1]
Maybe I'm wrong, but reading the README I thought that adding
```
1 DATA
2 EVEN DEAT
2 DATE FROM 1892 TO 1941
2 PLAC Gmunden, Gmunden, Oberösterreich, AUT
```
to a source record would enable the suggestion function, but there is nothing visible. The source (http://ahnen.hartenthaler.eu/tree/ahnen/source/S835/Sterberegister-Gmunden-1892-1941) is used for a DEAT event of a person (http://ahnen.hartenthaler.eu/tree/ahnen/individual/I9001/Marie-Hartenthaler). I tried to add an additional DEAT event at the same place and in the same time frame, but nothing was suggested. Where is my fault?

**Comment by ric2016** [comment]
The format is

```
1 DATA
2 EVEN DEAT
3 DATE FROM 1892 TO 1941
3 PLAC Gmunden, Gmunden, Oberösterreich, AUT
```

i.e. DATE and PLAC are under EVEN (note that you can have multiple EVENs, e.g. for different places and/or different time periods). With this adjustment, it should work. 

Note also that you don't have to edit the raw GEDCOM, you can enter all this as a fact (add the fact 'Data' at a source). 

I'll improve handling the EVEN types, currently you have to enter a string here (comma-separated for multiple EVENs).

**Comment by ric2016** [comment]
Note: I have updated the README: In particular the 'Data' fact may have to be activated for sources via the tree preferences, in order to be able to add it to sources (without having to use raw GEDCOM).

**Comment by hartenthaler** [comment]
Thank you! Now the README is more precise.

I modified my source as required. But still no research link is presented. I tried a more complex source [Kirchenbuch Köndringen](http://ahnen.hartenthaler.eu/tree/ahnen/source/S66/Kirchenbuch-Kondringen) but again no success when adding a new event of the specified type at the specified time and location.

Then I tried your example with a new person [Max Mustermann](http://ahnen.hartenthaler.eu/tree/ahnen/individual/X265/Max-Mustermann) and the source

```
1 DATA
2 EVEN CHR,MARR,BURI
3 DATE FROM 1765 TO 1852
3 PLAC Neuenkirchen (St. Bartholomäus)
2 EVEN CONF
3 DATE FROM 1841 TO 1852
3 PLAC Neuenkirchen (St. Bartholomäus)
```

When adding a CHR event webtrees shows "Searching" and some miliseconds later again "No results found". So the module is active, but does not find a match. Why? How can I help to debug?

**Comment by ric2016** [comment]
Thanks for testing - This was a bug: The place itself was not taken into account, only its parent places. This is fixed by [this commit](https://github.com/vesta-webtrees-2-custom-modules/vesta_research_suggestions/commit/bb6a08d18dcfae2badf410f9ab8c6a202d5ada13#diff-5673ff7f7b427674ae537193e3a0b69e). 

Note also that Christening and Baptism (CHR/BAPM) are not handled equivalently everywhere yet, I'll change this as well. (Technically these are different event types, but they are often used interchangeably - e.g. they have the same German translation)

**Comment by ric2016** [comment]
Should be fixed in latest release.
