### ISSUE TITLE
Source list shows additional column "Event data?"; column title is not translated

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_research_suggestions#21]
Observed with webtrees 2.0.16 and Vesta Research Suggestions 2.0.16.6.0.

The background is that I have started to use specific DATA/EVEN/DATE structures for sources. Something like this:

0 @s1@ SOUR
1 TITL Citizen Record
1 DATA
2 EVEN BIRT
3 DATE FROM 1676 TO 1855
3 PLAC New York

After introducing this new data to some of my sources, a new column showed up in the source list, see screenshot. The title of the column is ""Event data?" and the column contains a checkmark if the related source contains the above data structure. So far, this seems to be o.k..

However, the column title "Event data?" is always shown in English and is never translated, when choosing other languages.

Is this column title missing in all of the translation files or is it a bug?

![Source Event data 2](https://user-images.githubusercontent.com/81484983/136689769-ac0ccdb4-39a9-44f3-93cf-4ffa724ec361.jpg)
![Source Event data](https://user-images.githubusercontent.com/81484983/136689772-5516cc8a-a0ba-4bc8-aeba-8dd0a75759c0.jpg)

**Comment by ric2016** [comment]
Thank you for the note - The string was indeed missing in the translation files, I've fixed that now.
It may now be translated via weblate, see e.g. [here](https://hosted.weblate.org/translate/vesta-webtrees-custom-modules/vesta-research-suggestions/de/?offset=1&q=event+data). Translations will be included in the next release (as usual).
