### ISSUE TITLE
v2.1.0.0.0 - Untranslated text

### ISSUE THREAD

**Issue by TheDutchJewel** [vesta-webtrees-2-custom-modules/vesta_research_suggestions#29]
After adding the latest version of vesta modules (2.1.0.0.0) to webtrees v2.1.0, I see some untranslated text in Control Panel > Tree > Preferences, while the translation is available in the module:

![afbeelding](https://user-images.githubusercontent.com/46184729/164318969-47a5c05d-b351-45b0-bae7-9734d2e9bfbc.png)

**Comment by ric2016** [comment]
The string was previously translated in webtrees core, and was excluded in Vesta in order to avoid duplication. Added now in code (not released yet).

**Comment by ric2016** [comment]
Fixed in latest release.
