### ISSUE TITLE
v2.1.0.0.0 - Error message when clicking on the Family tree icon

### ISSUE THREAD

**Issue by TheDutchJewel** [vesta-webtrees-2-custom-modules/vesta_research_suggestions#31]
When I click on the Family tree icon in the header of webtrees v2.1.0, I get this error about the Vesta Research Suggestions Module:

![afbeelding](https://user-images.githubusercontent.com/46184729/164457578-a546444c-4909-4fba-a62f-581a2d1181c0.png)

**Comment by ric2016** [comment]
Although the Vesta module appears in the stack trace, the actual issue is likely in webtrees core.

Can you test whether this still occurs if this (or better: all) Vesta modules are disabled?

**Comment by TheDutchJewel** [comment]
You're right, then I get the error message too, just with no mention of the Vesta modules:

![afbeelding](https://user-images.githubusercontent.com/46184729/164463109-5cd7e3f2-0d93-479b-899b-a4f4da80518e.png)

I have created a new issue for this on the webtrees tracker: [#4327](https://github.com/fisharebest/webtrees/issues/4327).
