### ISSUE TITLE
Cannot merge sources

### ISSUE THREAD

**Issue by ric2016** [vesta-webtrees-2-custom-modules/vesta_research_suggestions#4]
Reported as webtrees #3361.
Will be fixed immediately.

**Comment by ro-la** [comment]
Also it is not possible to choose a source, when editing a fact or event.

Ladislav

**Comment by ric2016** [comment]
> Also it is not possible to choose a source, when editing a fact or event.

This should be fixed already in 2.0.6.0.1?

**Comment by ric2016** [comment]
Fixed in latest release 2.0.6.0.2.
