### ISSUE TITLE
'Research Suggestions' checkbox does not appear

### ISSUE THREAD

**Issue by dliessi** [vesta-webtrees-2-custom-modules/vesta_research_suggestions#54]
I have the latest version of Webtrees (2.1.20) and all Vesta modules (latest version) are installed and enabled. The 'Research Suggestions' checkbox does not appear in the 'Facts and events' tab.

**Comment by ric2016** [comment]
It only appears if there are suggestions available for the respective person (similar to the other checkboxes).
